#! /usr/bin/perl

# gcc -save-temps -fomit-frame-pointer -Os -Wall -c jpg.c
# convert: .data -> .text
# add: .code16gcc
# convert: .local/.comm foo,bar,??? -> foo: .space bar,0
# remove: .size, .type, .align
# remove .section .note...
# remove .ident

# manually:
# tmp_img -> %fs
# fix getbyte, getword -> %es

@f = (<>);

for (@f) {
  undef $_ if /^\s*\.(size|align|text|section|ident|local|data|file)/;
  $_ = "\n" if /^\s*\.type/;
  if(/^\s*\.globl/) {
    push @globl, "\t$_";
    undef $_;
  }

  if(/^\s*\.comm\s+(\S+),(\d+),\d+\s*$/) {
    push @comm, "\n$1:\n\t.space\t$2,0\n";
    undef $_;
  }
}

print "\t.file\t\"jpeg.S\"\n" . "\t.text\n" . "\t\.code16gcc\n\n";
print @globl;
print @comm;
print @f;

