% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
%
% Keyboard mappings.
%
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -


% keymap layout (diff to us map):
%
% key_code, plain, shift, altgr
%

/.km.locale 0 def
/.km.map    1 def

%% include keymap.cs_CZ.inc
%% include keymap.da_DK.inc
%% include keymap.de_DE.inc
%% include keymap.et_EE.inc
%% include keymap.el_GR.inc
%% include keymap.es_ES.inc
%% include keymap.fr_FR.inc
%% include keymap.hu_HU.inc
%% include keymap.it_IT.inc
%% include keymap.ja_JP.inc
%% include keymap.nb_NO.inc
%% include keymap.pl_PL.inc
%% include keymap.pt_BR.inc
%% include keymap.pt_PT.inc
%% include keymap.ru_RU.inc
%% include keymap.sk_SK.inc
%% include keymap.sl_SI.inc
%% include keymap.sv_SE.inc
%% include keymap.tr_TR.inc

% array must not be empty
/keymaps [
  [ "cs_CZ" keymap.cs_CZ ]
  [ "da_DK" keymap.da_DK ]
  [ "de_DE" keymap.de_DE ]
  [ "et_EE" keymap.et_EE ]
  [ "el_GR" keymap.el_GR ]
  [ "es_ES" keymap.es_ES ]
  [ "fr_FR" keymap.fr_FR ]
  [ "hu_HU" keymap.hu_HU ]
  [ "it_IT" keymap.it_IT ]
  [ "ja_JP" keymap.ja_JP ]
  [ "nb_NO" keymap.nb_NO ]
  [ "pl_PL" keymap.pl_PL ]
  [ "pt_BR" keymap.pt_BR ]
  [ "pt_PT" keymap.pt_PT ]
  [ "ru_RU" keymap.ru_RU ]
  [ "sk_SK" keymap.sk_SK ]
  [ "sl_SI" keymap.sl_SI ]
  [ "sv_SE" keymap.sv_SE ]
  [ "tr_TR" keymap.tr_TR ]
] def


